/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e9f25bb3-2073-4cf7-a601-593cd0437f27",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5AMQEbqiv",
    "aws_user_pools_web_client_id": "2d461ngijvn5kftqcu25b43uqo",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ezdj65hnqrdobpses46akd22gy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "pointerapi",
            "endpoint": "https://waz8dfv76i.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "dbServices",
            "endpoint": "https://brdht1pagg.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "UserProfile-dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
